# This starts a nginx webserver from a pre-built image.
#
# The server listens on port 8080 on your machine, 
# but this is forwarded to port 80 (the standard HTTP port) in the container.
#
# The server will serve files from the current directory "./".
#
# By default the root path http://localhost:8080/ serves the file index.html
web:
  image: nginx
  volumes:
   - ./:/usr/share/nginx/html:ro
  ports:
   - "8080:80"
  environment:
   - NGINX_PORT=80
